### ISSUE TITLE
not able to unlock car

### ISSUE THREAD

**Issue by xraver** [ReneNulschDE/mbapipy#1]
First of all very good work! i've very appreciate this plugin!
I'm trying to unlock my car using this plugin with no success.
I'm able to lock but not to unlock.

Seems that something is going wrong with PIN. after several tries i had to reset my pin using mercedes me app.

Below you can find an example of the error from log file

thanks

2019-06-07 22:13:23 ERROR (Thread-2) [custom_components.mercedesmeapi.apicontroller] Connection failed with http code 403
NoneType: None
2019-06-07 22:13:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140373626142672] 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/var/lib/homeassistant/lib/python3.5/site-packages/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/var/lib/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/var/lib/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/var/lib/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/var/lib/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/var/lib/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/homeassistant/.homeassistant/custom_components/mercedesmeapi/lock.py", line 69, in unlock
    self._data.unlock(self._vin, "2568")
  File "/var/lib/homeassistant/.homeassistant/custom_components/mercedesmeapi/apicontroller.py", line 295, in unlock
    return self._execute_car_action(CAR_UNLOCK_URL, car_id, 'car unlock', pin)
  File "/var/lib/homeassistant/.homeassistant/custom_components/mercedesmeapi/apicontroller.py", line 337, in _execute_car_action
    if result.get("status") == 'PENDING':
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by ReneNulschDE** [comment]
Hi,
could you please recheck. I've fixed the PIN issue.
BR
Rene

**Comment by xraver** [comment]
Works!!! Fantastic!!
Thanks to much!

Il Mar 11 Giu 2019, 11:16 Rene Nulsch <notifications@github.com> ha scritto:
