### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by xraver** [ReneNulschDE/mbapipy#26]
Hi.
the integration worked well up to yesterday.
From yesterday, when I try to start home assistant I receive the following notification:
> The following integrations and platforms could not be set up:
> mercedesmeapi
> Please check your config.

Some additional informations about home assistant:
> arch | x86_64
> dev | false
> docker | true
> hassio | false
> installation_type | Home Assistant Container
> os_name | Linux
> os_version | 4.19.0-9-amd64
> python_version | 3.8.3
> timezone | Europe/Rome
> version | 0.113.2
> virtualenv | false

Below the log from home assistant:
> 2020-08-01 10:14:50 ERROR (MainThread) [homeassistant.setup] Error during setup of component mercedesmeapi
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
>     response.begin()
>   File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
>     version, status, reason = self._read_status()
>   File "/usr/local/lib/python3.8/http/client.py", line 264, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
>     return self.read(nbytes, buffer)
>   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
>     return self._sslobj.read(len, buffer)
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
>     response.begin()
>   File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
>     version, status, reason = self._read_status()
>   File "/usr/local/lib/python3.8/http/client.py", line 264, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
>     return self.read(nbytes, buffer)
>   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
>     return self._sslobj.read(len, buffer)
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
>     result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
>   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/mercedesmeapi/__init__.py", line 107, in setup
>     mercedesme_api = Controller(
>   File "/config/custom_components/mercedesmeapi/apicontroller.py", line 342, in __init__
>     self._get_cars()
>   File "/config/custom_components/mercedesmeapi/apicontroller.py", line 540, in _get_cars
>     response = self.session.get(ME_STATUS_URL(URL_USR_API(self.region)),
>   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Do you have any idea of this problem?
i've tried to revert to an old backup but is the same.
thanks

**Comment by xraver** [comment]
Mercedes has disabled the API endpoints...
this is not an application issue... 
hope to find a solution
